//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollaxis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLogin
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string SecretQuestion1 { get; set; }
        public string SecretQuestion2 { get; set; }
        public string SecretAns1 { get; set; }
        public string SecretAns2 { get; set; }
        public int Status { get; set; }
    }
}
