//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollaxis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public int AddressID { get; set; }
        public int ManagerID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<int> SalaryClassID { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<short> VacationHours { get; set; }
        public Nullable<short> SickLeaveHours { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public Nullable<double> NetPay { get; set; }
    }
}
