//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollaxis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryClass
    {
        public int SalaryClassID { get; set; }
        public string SalaryClass1 { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Bonus { get; set; }
        public Nullable<double> MedicalAllowance { get; set; }
        public Nullable<double> TravelAllowance { get; set; }
        public Nullable<double> LaundryAllowance { get; set; }
        public Nullable<double> ClothingAllowance { get; set; }
        public Nullable<double> EducationAllowance { get; set; }
        public Nullable<double> MealAllowance { get; set; }
    }
}
